#pragma config(Sensor, S1,     irSensor,       sensorEV3_IRSensor, modeEV3IR_Remote)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, reversed, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorD,           ,             tmotorNXT, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"
#pragma DebuggerWindows("joystickSimple")

task main()
{


	while (true)
	{
		float k = 1.28;
 	 getJoystickSettings(joystick);
 	 if(joystick.joy1_TopHat == -1){

 	 motor[motorA] = (joystick.joy1_x1+joystick.joy1_y1)/k;
 	 motor[motorB] = (joystick.joy1_x2+joystick.joy1_y2)/k;
 	 motor[motorC] = (-joystick.joy1_x2+joystick.joy1_y2)/k;
 	 motor[motorD] = (-joystick.joy1_x1+joystick.joy1_y1)/k;}
   if(joystick.joy1_TopHat == 0)
 	 {
 	   motor[motorA]=100;
 	   motor[motorB]=100;
 	   motor[motorC]=100;
 	   motor[motorD]=100;
 	 }
 	 if(joystick.joy1_TopHat == 1)
 	 {
 	   motor[motorA]=100;
 	   motor[motorB]=100;
 	   motor[motorC]=50;
 	   motor[motorD]=50;
 	 }
 	 if(joystick.joy1_TopHat == 2)
 {
   motor[motorA]=100;
   motor[motorB]=100;
   motor[motorC]=-100;
   motor[motorD]=-100;
 }
 	if(joystick.joy1_TopHat == 3)
 	{
 		motor[motorA]=-100;
 		motor[motorB]=-100;
 		motor[motorC]=-50;
 		motor[motorD]=-50;
 	}
 	if(joystick.joy1_TopHat == 4)
 	{
 		motor[motorA]=-100;
 		motor[motorB]=-100;
 		motor[motorC]=-100;
 		motor[motorD]=-100;
 	}
 	if(joystick.joy1_TopHat == 5)
 	{
 		motor[motorA]=-50;
 		motor[motorB]=-50;
 		motor[motorC]=-100;
 		motor[motorD]=-100;
 	}
 	if(joystick.joy1_TopHat == 6)
 	{
 		motor[motorA]=-100;
 		motor[motorB]=-100;
 		motor[motorC]=100;
 		motor[motorD]=100;
 	}
 	if(joystick.joy1_TopHat == 7)
 	{
 		motor[motorA]=50;
 		motor[motorB]=50;
 		motor[motorC]=100;
 		motor[motorD]=100;
 	}

 	 sleep(1);
	}
}
