#pragma config(Sensor, S1,     ,               sensorLightActive)
#pragma config(Sensor, S4,     ,               sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#pragma DebuggerWindows("joystickSimple")
int err, u, sens1, sens2;
	float k=20;



void down()
{
	nMotorEncoder[motorC]=0;
	while(nMotorEncoder[motorC] > -450)
{
	motor[motorC]=-50;
	sleep(1);
}
motor[motorA]=0;
}

void up()
{
	nMotorEncoder[motorC]=0;
	while(nMotorEncoder[motorC] < 450)
{
	motor[motorC]=50;
	sleep(1);
}
motor[motorA]=0;
}




void detected()
{
	nMotorEncoder[motorA]=0;
  while(nMotorEncoder[motorA] > 500)
  {
  	motor[motorA]=-50;
  	motor[motorD]=-50;
  	sleep(1);
  }
  up();
}



void line()
{
		sens1=SensorValue[S1];
		sens2=SensorValue[S4];
   	err=sens1-sens2;
   	u=err*k;
		motor[motorD]=-100+u;
		motor[motorA]=-100-u;
		if(SensorValue[S3] < 6)
		{
			detected();
		}
  	sleep(1);

}






task main()
{


	while (true)
	{
 	 getJoystickSettings(joystick);
 	 //if (SensorValue[S2] < 13) detected();
 	 motor[motorA] = joystick.joy1_y1;
 	 motor[motorD] = joystick.joy1_y2;
	//if(joy1Btn(Btn5) == 1)
 	 if(joy1Btn(Btn4) == 1)
 	 {
 	   up();
 	 }
 	 else if(joy1Btn(Btn2) == 1)
 	 {
 	   down();
 	 }
 	 else {motor[motorC]=0;}
	/*if(joy1Btn(Btn2) == 1)
 	 {
 	  k=-1;
 	 }
 	 else if(joy1Btn(Btn3) == 1)
 	 {
 	   k=1;
 	 }*/
		if (joy1Btn(Btn10)==1)
		{
			while(joy1Btn(Btn9) != 1){ getJoystickSettings(joystick); line();}
		}
	displayCenteredBigTextLine(5, "%f", getBatteryVoltage());
 	 sleep(1);
	}
}
