#pragma config(Sensor, S1,     ,               sensorLightActive)
#pragma config(Sensor, S4,     ,               sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#pragma DebuggerWindows("joystickSimple")
int err,
		u,
		sens1,
		sens2,
    black_line_limit=10,
		vline=50;

float k=35;

void down()
{
	nMotorEncoder[motorC]=0;
	while(nMotorEncoder[motorC] > -420)
{
	motor[motorC]=-20;
	sleep(1);
}
motor[motorC]=0;
}

void up()
{
	nMotorEncoder[motorC]=0;
	while(nMotorEncoder[motorC] < 420)
{
	motor[motorC]=20;
	sleep(1);
}
motor[motorC]=0;
}




void detected()
{
	motor[motorA]=0;
  motor[motorD]=0;

 nMotorEncoder[motorA]=0;

 while(nMotorEncoder[motorA] > -50)
  {
  	motor[motorA]=-20;
  	motor[motorD]=-20;
  	sleep(1);
  }

	motor[motorA]=0;
  motor[motorD]=0;

  up();
  }



void line()
{
		sens1=SensorValue[S1];
		sens2=SensorValue[S4];
   	err=sens1-sens2;
   	u=err*k;
		motor[motorD]=-vline+u;
		motor[motorA]=-vline-u;

  	sleep(1);
}

void tocross()
{
	while(true){if(SensorValue[S1] < 17 && SensorValue[S4] < 17)break;
		line();
		sleep(1);
	}
	motor[motorA]=0;
	motor[motorD]=0;
	down();
}

task main()
{


	while (true)
	{
 	 getJoystickSettings(joystick);
 	 //if (SensorValue[S2] < 13) detected();
 	 if (abs(joystick.joy1_y1) < 5){motor[motorA]=0;}
 	 else {motor[motorA] = joystick.joy1_y1;}
 	 if(abs(joystick.joy1_y2) < 5){motor[motorD]=0;}
 	 else {motor[motorD] = joystick.joy1_y2;}
	//if(joy1Btn(Btn5) == 1)
 	 if(joy1Btn(Btn4) == 1)
 	 {
 	   up();
 	 }
 	 else if(joy1Btn(Btn2) == 1)
 	 {
 	   down();
 	 }
 	 else {motor[motorC]=0;}
	/*if(joy1Btn(Btn2) == 1)
 	 {
 	  k=-1;
 	 }
 	 else if(joy1Btn(Btn3) == 1)
 	 {
 	   k=1;
 	 }*/
		if (joy1Btn(Btn10)==1)  //btn start
		{ down();
			while(joy1Btn(Btn9) != 1)
				{ getJoystickSettings(joystick);
					line();
					if(SensorValue[S3] < 6)
								{  detected();
									 tocross();   break;
       		}
				}
		}
	displayCenteredBigTextLine(5, "%f", getBatteryVoltage());
 	 sleep(1);
	}
}
