#pragma config(Sensor, S1,     banka,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     senter,         sensorEV3_Color)
#pragma config(Sensor, S3,     left2,          sensorEV3_Color)
#pragma config(Sensor, S4,     right2,         sensorEV3_Color)
#pragma config(Motor,  motorA,          right,         tmotorEV3_Large, openLoop, driveRight, encoder)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, openLoop, driveLeft, encoder)
#pragma config(Motor,  motorD,          klehni,        tmotorEV3_Medium, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
	int i=getColorReflected(senter);
	while(true)
	{
		//cenr datchikport2
		//chernij 9
		//belij 75
		if(i>33)
		{
			moveMotorTarget(left, 45, 25);
			moveMotorTarget(right, 20, 25);
		}
		else
		{
			moveMotorTarget(left, 20, 25);
			moveMotorTarget(right, 45, 25);
		}
	}
}
