#pragma config(Sensor, S1,     ,               sensorLightActive)
#pragma config(Sensor, S4,     ,               sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#pragma DebuggerWindows("joystickSimple")
int	k=10;



task main()
{


	while (true)
	{
 	 getJoystickSettings(joystick);
 	 //if (SensorValue[S2] < 13) detected();
 	 if (abs(joystick.joy1_y1) < 5){motor[motorB]=0;}
 	 else {motor[motorB] = joystick.joy1_y1/k;}
 	 if(abs(joystick.joy1_y2) < 5){motor[motorC]=0;}
 	 else {motor[motorC] = joystick.joy1_y2/k;}
	//if(joy1Btn(Btn5) == 1)
	/*if(joy1Btn(Btn2) == 1)
 	 {
 	  k=-1;
 	 }
 	 else if(joy1Btn(Btn3) == 1)
 	 {
 	   k=1;
 	 }*/
	displayCenteredBigTextLine(5, "%f", getBatteryVoltage());
 	 sleep(1);
	}
}
