#pragma config(Sensor, S1,     ,               sensorLightActive)
#pragma config(Sensor, S4,     ,               sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#pragma DebuggerWindows("joystickSimple")
int err,
		u,
		sens1,
		sens2,
    grey=27,
		vline=70;

float k=20;

void down()
{
	nMotorEncoder[motorC]=0;
	while(nMotorEncoder[motorC] > -400)
{
	motor[motorC]=-20;
	sleep(1);
}
motor[motorC]=0;
}


void downline()
{
	nMotorEncoder[motorC]=0;
	while(nMotorEncoder[motorC] > -150)
{
	motor[motorC]=-20;
	sleep(1);
}
motor[motorC]=0;
}

void up()
{
	nMotorEncoder[motorC]=0;
	while(nMotorEncoder[motorC] < 400)
{
	motor[motorC]=20;
	sleep(1);
}
motor[motorC]=0;
}

void upline()
{
	nMotorEncoder[motorC]=0;
	while(nMotorEncoder[motorC] < 200)
{
	motor[motorC]=20;
	sleep(1);
}
motor[motorC]=0;
}




void detected()
{
	motor[motorA]=0;
  motor[motorD]=0;

 nMotorEncoder[motorA]=0;


  	motor[motorA]=-1;
  	motor[motorD]=-1;
  	sleep(700);
	motor[motorA]=0;
  motor[motorD]=0;
sleep(300);
  up();
  sleep(3000);
  down();
  upline();
  }



void line()
{
		sens1=SensorValue[S1];
		sens2=SensorValue[S4];
   	err=sens1-sens2;
   	u=err*k;
		motor[motorD]=-vline+u;
		motor[motorA]=-vline-u;

  	sleep(1);
}

void lineforw()
{
	while(true)
	{
		getJoystickSettings(joystick);
		if(SensorValue[S2] <= grey+1 && SensorValue[S2] >= grey-1)
   {
     motor[motorA]=50;
     motor[motorD]=50;
   }
   else if(SensorValue[S2] < grey)
   {
     motor[motorA]=50;
     motor[motorD]=0;
   }
   else if(SensorValue[S2] > grey)
   {
     motor[motorA]=0;
     motor[motorD]=50;
   }
   sleep(1);}
}

void tocross()
{
	while(true){if(SensorValue[S1] < 17 && SensorValue[S4] < 17)break;
		line();
		sleep(1);
	}
	motor[motorA]=0;
	motor[motorD]=0;
	downline();
}

task main()
{


	while (true)
	{
 	 getJoystickSettings(joystick);
 	 //if (SensorValue[S2] < 13) detected();
 	 if (abs(joystick.joy1_y1) < 5){motor[motorA]=0;}
 	 else {motor[motorA] = joystick.joy1_y1;}
 	 if(abs(joystick.joy1_y2) < 5){motor[motorD]=0;}
 	 else {motor[motorD] = joystick.joy1_y2;}
	//if(joy1Btn(Btn5) == 1)
 	 if(joy1Btn(Btn4) == 1)
 	 {
 	   up();
 	 }
 	 else if(joy1Btn(Btn2) == 1)
 	 {
 	   down();
 	 }
 	 else {motor[motorC]=0;}
		if (joy1Btn(Btn10)==1)  //btn start
		{ down();
			while(joy1Btn(Btn9) != 1)
				{ getJoystickSettings(joystick);
					line();
					if(SensorValue[S3] < 6)   //s3
								{  detected();
									 tocross();   break;
       		}
				}
		}
		if(joy1Btn(Btn6) == 1)
		{
			lineforw();
		}
	displayCenteredBigTextLine(5, "%f", getBatteryVoltage());
 	 sleep(1);
	}
}
